title: Anurag Guda
logo: "/images/round.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  <br><br>
github:
  github_url: https://github.com/angudadevops
  LinkedIn_url: https://www.linkedin.com/in/anuragguda/
theme: jekyll-theme-minima
